# Generated by Django 5.2.7 on 2025-11-05 13:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Background",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField()),
                ("skill_proficiencies", models.CharField(max_length=200)),
                ("tool_proficiencies", models.CharField(blank=True, max_length=200)),
                (
                    "languages",
                    models.IntegerField(
                        default=0, help_text="Number of additional languages"
                    ),
                ),
                ("equipment", models.TextField()),
                ("feature", models.CharField(max_length=100)),
                ("feature_description", models.TextField()),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CharacterClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField()),
                (
                    "hit_die",
                    models.IntegerField(help_text="Hit die (e.g., 6 for d6, 8 for d8)"),
                ),
                (
                    "primary_ability",
                    models.CharField(
                        help_text="Primary ability scores", max_length=100
                    ),
                ),
                ("saving_throw_proficiencies", models.CharField(max_length=100)),
                ("armor_proficiencies", models.TextField(blank=True)),
                ("weapon_proficiencies", models.TextField(blank=True)),
                ("tool_proficiencies", models.TextField(blank=True)),
                (
                    "skill_choices",
                    models.TextField(help_text="Available skill choices"),
                ),
                (
                    "num_skills",
                    models.IntegerField(
                        default=2, help_text="Number of skills to choose"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Character Classes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField()),
                ("speed", models.IntegerField(default=30)),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("Small", "Small"),
                            ("Medium", "Medium"),
                            ("Large", "Large"),
                        ],
                        default="Medium",
                        max_length=20,
                    ),
                ),
                ("strength_bonus", models.IntegerField(default=0)),
                ("dexterity_bonus", models.IntegerField(default=0)),
                ("constitution_bonus", models.IntegerField(default=0)),
                ("intelligence_bonus", models.IntegerField(default=0)),
                ("wisdom_bonus", models.IntegerField(default=0)),
                ("charisma_bonus", models.IntegerField(default=0)),
                (
                    "traits",
                    models.TextField(blank=True, help_text="Special racial traits"),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Spell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "level",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(9),
                        ]
                    ),
                ),
                (
                    "school",
                    models.CharField(
                        choices=[
                            ("Abjuration", "Abjuration"),
                            ("Conjuration", "Conjuration"),
                            ("Divination", "Divination"),
                            ("Enchantment", "Enchantment"),
                            ("Evocation", "Evocation"),
                            ("Illusion", "Illusion"),
                            ("Necromancy", "Necromancy"),
                            ("Transmutation", "Transmutation"),
                        ],
                        max_length=50,
                    ),
                ),
                ("casting_time", models.CharField(max_length=100)),
                ("range", models.CharField(max_length=100)),
                ("components", models.CharField(max_length=200)),
                ("duration", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "classes",
                    models.CharField(
                        help_text="Classes that can cast this spell", max_length=200
                    ),
                ),
            ],
            options={
                "ordering": ["level", "name"],
            },
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("player_name", models.CharField(blank=True, max_length=100)),
                (
                    "level",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "strength",
                    models.IntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "dexterity",
                    models.IntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "constitution",
                    models.IntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "intelligence",
                    models.IntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "wisdom",
                    models.IntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "charisma",
                    models.IntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                ("max_hit_points", models.IntegerField(default=0)),
                ("current_hit_points", models.IntegerField(default=0)),
                ("temporary_hit_points", models.IntegerField(default=0)),
                ("acrobatics", models.BooleanField(default=False)),
                ("animal_handling", models.BooleanField(default=False)),
                ("arcana", models.BooleanField(default=False)),
                ("athletics", models.BooleanField(default=False)),
                ("deception", models.BooleanField(default=False)),
                ("history", models.BooleanField(default=False)),
                ("insight", models.BooleanField(default=False)),
                ("intimidation", models.BooleanField(default=False)),
                ("investigation", models.BooleanField(default=False)),
                ("medicine", models.BooleanField(default=False)),
                ("nature", models.BooleanField(default=False)),
                ("perception", models.BooleanField(default=False)),
                ("performance", models.BooleanField(default=False)),
                ("persuasion", models.BooleanField(default=False)),
                ("religion", models.BooleanField(default=False)),
                ("sleight_of_hand", models.BooleanField(default=False)),
                ("stealth", models.BooleanField(default=False)),
                ("survival", models.BooleanField(default=False)),
                ("alignment", models.CharField(blank=True, max_length=50)),
                ("personality_traits", models.TextField(blank=True)),
                ("ideals", models.TextField(blank=True)),
                ("bonds", models.TextField(blank=True)),
                ("flaws", models.TextField(blank=True)),
                ("features_and_traits", models.TextField(blank=True)),
                ("equipment", models.TextField(blank=True)),
                ("copper_pieces", models.IntegerField(default=0)),
                ("silver_pieces", models.IntegerField(default=0)),
                ("electrum_pieces", models.IntegerField(default=0)),
                ("gold_pieces", models.IntegerField(default=0)),
                ("platinum_pieces", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "background",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="characters.background",
                    ),
                ),
                (
                    "character_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="characters.characterclass",
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="characters.race",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CharacterSpell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_prepared", models.BooleanField(default=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spells",
                        to="characters.character",
                    ),
                ),
                (
                    "spell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="characters.spell",
                    ),
                ),
            ],
            options={
                "ordering": ["spell__level", "spell__name"],
                "unique_together": {("character", "spell")},
            },
        ),
    ]
