# Generated by Django 5.2.7 on 2025-11-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Weapon", "Weapon"),
                            ("Armor", "Armor"),
                            ("Adventuring Gear", "Adventuring Gear"),
                            ("Tool", "Tool"),
                            ("Mount", "Mount"),
                            ("Vehicle", "Vehicle"),
                            ("Potion", "Potion"),
                            ("Scroll", "Scroll"),
                            ("Wondrous Item", "Wondrous Item"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "cost_gold",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Weight in pounds",
                        max_digits=6,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Equipment",
                "ordering": ["category", "name"],
            },
        ),
        migrations.AddField(
            model_name="character",
            name="equipment_items",
            field=models.ManyToManyField(
                blank=True, related_name="characters", to="characters.equipment"
            ),
        ),
    ]
