# Generated by Django 5.2.7 on 2025-11-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0002_equipment_character_equipment_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="ability_score_improvements",
            field=models.TextField(
                blank=True, help_text="Record of ASI choices by level"
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="feats",
            field=models.TextField(
                blank=True, help_text="Feats acquired through level advancement"
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="hit_dice_used",
            field=models.IntegerField(
                default=0, help_text="Number of hit dice used (for short rest recovery)"
            ),
        ),
    ]
