# Generated by Django 5.2.7 on 2025-11-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "characters",
            "0003_character_ability_score_improvements_character_feats_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Feat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "prerequisite",
                    models.CharField(
                        blank=True,
                        help_text="Prerequisites to take this feat",
                        max_length=200,
                    ),
                ),
                ("description", models.TextField()),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="character",
            name="feats",
        ),
        migrations.AddField(
            model_name="character",
            name="feats",
            field=models.ManyToManyField(
                blank=True, related_name="characters", to="characters.feat"
            ),
        ),
    ]
