# Generated by Django 5.2.7 on 2025-11-05 16:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0004_feat_remove_character_feats_character_feats"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="conditions",
            field=models.TextField(
                blank=True, help_text="Active conditions (comma-separated)"
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="death_save_failures",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="death_save_successes",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="exhaustion_level",
            field=models.IntegerField(
                default=0,
                help_text="Exhaustion level (0-6)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(6),
                ],
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="inspiration",
            field=models.BooleanField(default=False, help_text="Has inspiration"),
        ),
        migrations.AddField(
            model_name="character",
            name="languages",
            field=models.TextField(
                blank=True, help_text="Languages known (comma-separated)"
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="tool_proficiencies",
            field=models.TextField(
                blank=True, help_text="Tool proficiencies (comma-separated)"
            ),
        ),
    ]
