# Generated by Django 5.2.7 on 2025-11-05 16:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "characters",
            "0005_character_conditions_character_death_save_failures_and_more",
        ),
    ]

    operations = []
