# Generated by Django 5.2.7 on 2025-11-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0006_add_spell_slots"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="spell_slots_1_max",
            field=models.IntegerField(default=0, help_text="Max level 1 spell slots"),
        ),
        migrations.AddField(
            model_name="character",
            name="spell_slots_1_used",
            field=models.IntegerField(default=0, help_text="Used level 1 spell slots"),
        ),
        migrations.AddField(
            model_name="character",
            name="spell_slots_2_max",
            field=models.IntegerField(default=0, help_text="Max level 2 spell slots"),
        ),
        migrations.AddField(
            model_name="character",
            name="spell_slots_2_used",
            field=models.IntegerField(default=0, help_text="Used level 2 spell slots"),
        ),
        migrations.AddField(
            model_name="character",
            name="spell_slots_3_max",
            field=models.IntegerField(default=0, help_text="Max level 3 spell slots"),
        ),
        migrations.AddField(
            model_name="character",
            name="spell_slots_3_used",
            field=models.IntegerField(default=0, help_text="Used level 3 spell slots"),
        ),
        migrations.AddField(
            model_name="character",
            name="spell_slots_4_max",
            field=models.IntegerField(default=0, help_text="Max level 4 spell slots"),
        ),
        migrations.AddField(
            model_name="character",
            name="spell_slots_4_used",
            field=models.IntegerField(default=0, help_text="Used level 4 spell slots"),
        ),
        migrations.AddField(
            model_name="character",
            name="spell_slots_5_max",
            field=models.IntegerField(default=0, help_text="Max level 5 spell slots"),
        ),
        migrations.AddField(
            model_name="character",
            name="spell_slots_5_used",
            field=models.IntegerField(default=0, help_text="Used level 5 spell slots"),
        ),
        migrations.AddField(
            model_name="character",
            name="spell_slots_6_max",
            field=models.IntegerField(default=0, help_text="Max level 6 spell slots"),
        ),
        migrations.AddField(
            model_name="character",
            name="spell_slots_6_used",
            field=models.IntegerField(default=0, help_text="Used level 6 spell slots"),
        ),
        migrations.AddField(
            model_name="character",
            name="spell_slots_7_max",
            field=models.IntegerField(default=0, help_text="Max level 7 spell slots"),
        ),
        migrations.AddField(
            model_name="character",
            name="spell_slots_7_used",
            field=models.IntegerField(default=0, help_text="Used level 7 spell slots"),
        ),
        migrations.AddField(
            model_name="character",
            name="spell_slots_8_max",
            field=models.IntegerField(default=0, help_text="Max level 8 spell slots"),
        ),
        migrations.AddField(
            model_name="character",
            name="spell_slots_8_used",
            field=models.IntegerField(default=0, help_text="Used level 8 spell slots"),
        ),
        migrations.AddField(
            model_name="character",
            name="spell_slots_9_max",
            field=models.IntegerField(default=0, help_text="Max level 9 spell slots"),
        ),
        migrations.AddField(
            model_name="character",
            name="spell_slots_9_used",
            field=models.IntegerField(default=0, help_text="Used level 9 spell slots"),
        ),
        migrations.AddField(
            model_name="character",
            name="spellcasting_ability",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INT", "Intelligence"),
                    ("WIS", "Wisdom"),
                    ("CHA", "Charisma"),
                ],
                help_text="Primary spellcasting ability",
                max_length=3,
            ),
        ),
    ]
