# Generated by Django 5.2.7 on 2025-11-06 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0007_character_spell_slots_1_max_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="characterspell",
            options={},
        ),
        migrations.CreateModel(
            name="CharacterClassFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature_type",
                    models.CharField(
                        help_text="E.g., 'Fighting Style', 'Metamagic', 'Eldritch Invocations'",
                        max_length=100,
                    ),
                ),
                (
                    "feature_name",
                    models.CharField(
                        help_text="E.g., 'Archery', 'Careful Spell', 'Agonizing Blast'",
                        max_length=100,
                    ),
                ),
                ("feature_description", models.TextField(blank=True)),
                (
                    "level_gained",
                    models.IntegerField(
                        help_text="Character level when this feature was gained"
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_features",
                        to="characters.character",
                    ),
                ),
            ],
            options={
                "ordering": ["level_gained", "feature_type", "feature_name"],
            },
        ),
    ]
