# Generated by Django 5.2.7 on 2025-11-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0008_alter_characterspell_options_characterclassfeature"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="condition_immunities",
            field=models.TextField(
                blank=True, help_text="Condition immunities (e.g., Charmed, Frightened)"
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="damage_immunities",
            field=models.TextField(
                blank=True, help_text="Damage immunities (e.g., Fire, Poison)"
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="damage_resistances",
            field=models.TextField(
                blank=True, help_text="Damage resistances (e.g., Cold, Lightning)"
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="damage_vulnerabilities",
            field=models.TextField(
                blank=True, help_text="Damage vulnerabilities (e.g., Fire, Radiant)"
            ),
        ),
    ]
