# Generated by Django 5.2.7 on 2025-11-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0009_add_damage_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterclassfeature",
            name="sub_choice",
            field=models.CharField(
                blank=True,
                help_text="Secondary choice (e.g., 'Black Dragon', 'Arctic')",
                max_length=100,
            ),
        ),
    ]
