# Generated by Django 5.2.7 on 2025-11-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0010_add_sub_choice_to_class_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="subrace",
            field=models.CharField(
                blank=True,
                help_text="Subrace (e.g., Hill Dwarf, High Elf)",
                max_length=50,
            ),
        ),
    ]
