# Generated by Django 5.2.7 on 2025-11-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0011_add_subrace_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="acrobatics_expertise",
            field=models.BooleanField(
                default=False,
                help_text="Has expertise in Acrobatics (2x proficiency bonus)",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="animal_handling_expertise",
            field=models.BooleanField(
                default=False,
                help_text="Has expertise in Animal Handling (2x proficiency bonus)",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="arcana_expertise",
            field=models.BooleanField(
                default=False,
                help_text="Has expertise in Arcana (2x proficiency bonus)",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="athletics_expertise",
            field=models.BooleanField(
                default=False,
                help_text="Has expertise in Athletics (2x proficiency bonus)",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="deception_expertise",
            field=models.BooleanField(
                default=False,
                help_text="Has expertise in Deception (2x proficiency bonus)",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="history_expertise",
            field=models.BooleanField(
                default=False,
                help_text="Has expertise in History (2x proficiency bonus)",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="insight_expertise",
            field=models.BooleanField(
                default=False,
                help_text="Has expertise in Insight (2x proficiency bonus)",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="intimidation_expertise",
            field=models.BooleanField(
                default=False,
                help_text="Has expertise in Intimidation (2x proficiency bonus)",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="investigation_expertise",
            field=models.BooleanField(
                default=False,
                help_text="Has expertise in Investigation (2x proficiency bonus)",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="medicine_expertise",
            field=models.BooleanField(
                default=False,
                help_text="Has expertise in Medicine (2x proficiency bonus)",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="nature_expertise",
            field=models.BooleanField(
                default=False,
                help_text="Has expertise in Nature (2x proficiency bonus)",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="perception_expertise",
            field=models.BooleanField(
                default=False,
                help_text="Has expertise in Perception (2x proficiency bonus)",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="performance_expertise",
            field=models.BooleanField(
                default=False,
                help_text="Has expertise in Performance (2x proficiency bonus)",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="persuasion_expertise",
            field=models.BooleanField(
                default=False,
                help_text="Has expertise in Persuasion (2x proficiency bonus)",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="religion_expertise",
            field=models.BooleanField(
                default=False,
                help_text="Has expertise in Religion (2x proficiency bonus)",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="sleight_of_hand_expertise",
            field=models.BooleanField(
                default=False,
                help_text="Has expertise in Sleight of Hand (2x proficiency bonus)",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="stealth_expertise",
            field=models.BooleanField(
                default=False,
                help_text="Has expertise in Stealth (2x proficiency bonus)",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="survival_expertise",
            field=models.BooleanField(
                default=False,
                help_text="Has expertise in Survival (2x proficiency bonus)",
            ),
        ),
    ]
